'use client'

import { useMemo, useState } from 'react'
import { BarChart3, BookOpen, BriefcaseBusiness, ChevronDown, FileText, Menu, Search, Settings, ShieldCheck, Users, X, ArrowUpRight, Plus } from 'lucide-react'
import { ProfitCalculator, calculate, defaultValues, formatMoney, type CalculatorValues } from '@/components/marginmate/calculator'
import './marginmate.css'
import { MARGINMATE_CHECKOUT_URL } from './checkout'

type Screen = 'Overview' | 'Profit Guard' | 'Estimates' | 'Customers' | 'Jobs' | 'Price Book' | 'Job Profit' | 'Proposals' | 'Upgrade' | 'About'
const estimates = [
  { name: 'Bathroom Remodel', customer: 'Sarah Chen', cost: 4860, quote: 6500, margin: 25.2, status: 'MARGIN RISK', updated: 'Today, 9:42 AM' },
  { name: 'Kitchen Repair', customer: 'Tom Alvarez', cost: 1240, quote: 2100, margin: 41, status: 'SAFE', updated: 'Yesterday' },
  { name: 'Deck Restoration', customer: 'Jordan Lee', cost: 3920, quote: 3800, margin: -3.2, status: 'DO NOT QUOTE', updated: 'Mar 18, 2026' },
  { name: 'HVAC Replacement', customer: 'Priya Shah', cost: 5400, quote: 8300, margin: 34.9, status: 'MARGIN RISK', updated: 'Mar 17, 2026' },
]
const customers = [
  ['Sarah Chen', '2', '$12,400', 'Today'], ['Tom Alvarez', '1', '$2,100', 'Yesterday'], ['Jordan Lee', '1', '$3,800', 'Mar 18, 2026'], ['Priya Shah', '2', '$16,800', 'Mar 17, 2026'], ['Marcus Wright', '0', '$0', 'Mar 12, 2026']
]
const priceBook = [
  ['General Labor', 'Labor', 'hour', 65, 110], ['Electrician Labor', 'Labor', 'hour', 85, 145], ['Plumbing Labor', 'Labor', 'hour', 90, 155], ['Drywall', 'Materials', 'sq ft', 2.4, 5.5], ['Paint', 'Materials', 'gallon', 32, 68], ['Lumber', 'Materials', 'board', 8, 16], ['Fasteners', 'Materials', 'box', 12, 26], ['Equipment Rental', 'Equipment', 'day', 140, 250]
]

const nav = [
  ['Overview', BarChart3], ['Profit Guard', ShieldCheck], ['Estimates', FileText], ['Customers', Users], ['Jobs', BriefcaseBusiness], ['Price Book', BookOpen], ['Job Profit', BarChart3], ['Proposals', FileText]
] as const

export default function MarginMateApp() {
  const [screen, setScreen] = useState<Screen>('Overview')
  const [drawer, setDrawer] = useState(false)
  const [search, setSearch] = useState('')
  const [selectedEstimate, setSelectedEstimate] = useState(estimates[0])
  const [selectedCustomer, setSelectedCustomer] = useState<string | null>(null)
  const [saved, setSaved] = useState(false)
  const filteredBook = priceBook.filter(row => row.join(' ').toLowerCase().includes(search.toLowerCase()))
  const open = (next: Screen) => { setScreen(next); setDrawer(false) }
  return <div className="mm-app">
    <aside className={`mm-sidebar ${drawer ? 'is-open' : ''}`}>
      <div className="mm-sidebar-head"><div className="mm-product-mark">M</div><div><strong>MarginMate</strong><small>by Kalen Solves</small></div><button className="mm-close" onClick={() => setDrawer(false)} aria-label="Close navigation"><X size={18}/></button></div>
      <div className="mm-workspace"><span>WORKSPACE</span><strong>Miller Home Services</strong><small>DEMO MODE</small></div>
      <nav className="mm-side-nav" aria-label="Application navigation">{nav.map(([label, Icon]) => <button key={label} className={screen === label ? 'active' : ''} onClick={() => open(label)}><Icon size={17}/><span>{label}</span>{label === 'Profit Guard' && <i>Core</i>}</button>)}</nav>
      <div className="mm-sidebar-bottom"><button onClick={() => open('Upgrade')}><ShieldCheck size={16}/><span><strong>Full Access</strong><small>Unlock saved workflows</small></span><ArrowUpRight size={14}/></button><button onClick={() => open('About')}><Settings size={16}/>Settings</button><div className="mm-company">Kalen Solves <small>Business software, solved.</small></div></div>
    </aside>
    {drawer && <button className="mm-overlay" onClick={() => setDrawer(false)} aria-label="Close menu"/>}
    <main className="mm-main"><header className="mm-topbar"><button className="mm-menu-btn" onClick={() => setDrawer(true)} aria-label="Open navigation"><Menu size={20}/></button><div><span className="mm-breadcrumb">MILLER HOME SERVICES / DEMO</span><h1>{screen === 'Overview' ? 'Profit Dashboard' : screen}</h1></div><div className="mm-top-actions"><span className="mm-demo-badge">DEMO MODE</span><button className="mm-new" onClick={() => open('Estimates')}><Plus size={15}/> New Estimate</button><a className="mm-upgrade" href={MARGINMATE_CHECKOUT_URL} target="_blank" rel="noopener noreferrer">Get Full Access — $99</a></div></header><div className="mm-content">{screen === 'Overview' && <Overview onScreen={open} onEstimate={setSelectedEstimate}/>} {screen === 'Profit Guard' && <ProfitGuard/>} {screen === 'Estimates' && <Estimates onScreen={open} onEstimate={setSelectedEstimate} saved={saved} setSaved={setSaved}/>} {screen === 'Customers' && <Customers selected={selectedCustomer} setSelected={setSelectedCustomer}/>} {screen === 'Jobs' && <Jobs/>} {screen === 'Price Book' && <PriceBook search={search} setSearch={setSearch} rows={filteredBook}/>} {screen === 'Job Profit' && <JobProfit/>} {screen === 'Proposals' && <Proposal estimate={selectedEstimate}/>} {screen === 'Upgrade' && <Upgrade/>} {screen === 'About' && <About/>}</div></main>
  </div>
}

function PageIntro({ eyebrow, title, sub, action }: { eyebrow: string; title: string; sub: string; action?: React.ReactNode }) { return <div className="mm-page-intro"><div><span className="mm-eyebrow">{eyebrow}</span><h2>{title}</h2><p>{sub}</p></div>{action}</div> }
function Overview({ onScreen, onEstimate }: { onScreen: (s: Screen) => void; onEstimate: (e: typeof estimates[number]) => void }) { return <><PageIntro eyebrow="PROFIT DASHBOARD" title="Good morning." sub="Protect your margin before the quote goes out." action={<button className="mm-primary" onClick={() => onScreen('Estimates')}><Plus size={16}/> New Estimate</button>}/><div className="mm-sample"><span>Sample Business Data</span><span>All figures are fictional demo data for Miller Home Services.</span></div><div className="mm-stats"><Stat label="Quotes Checked" value="24"/><Stat label="Average Planned Margin" value="31.8%"/><Stat label="Margin Risk" value="6" tone="amber"/><Stat label="Potential Underpricing" value="$4,280" tone="red"/></div><section className="mm-panel"><div className="mm-panel-head"><div><span className="mm-eyebrow">RECENT ESTIMATES</span><h3>Quote activity</h3></div><button className="mm-text-btn" onClick={() => onScreen('Estimates')}>View all <ArrowUpRight size={14}/></button></div><EstimateTable onEstimate={onEstimate}/></section><div className="mm-two-cards"><button className="mm-quick-card" onClick={() => onScreen('Profit Guard')}><ShieldCheck size={20}/><span><strong>Run Profit Guard</strong><small>Check a quote against your target margin.</small></span><ArrowUpRight size={16}/></button><button className="mm-quick-card" onClick={() => onScreen('Job Profit')}><BarChart3 size={20}/><span><strong>Review job profitability</strong><small>Compare estimated and actual costs.</small></span><ArrowUpRight size={16}/></button></div></> }
function Stat({ label, value, tone='' }: { label:string;value:string;tone?:string }) { return <div className={`mm-stat ${tone}`}><span>{label}</span><strong>{value}</strong><small>vs. last 30 days <b>+12%</b></small></div> }
function EstimateTable({ onEstimate }: { onEstimate: (e: typeof estimates[number]) => void }) { return <div className="mm-table-wrap"><table className="mm-table"><thead><tr><th>Estimate</th><th>Customer</th><th>True Cost</th><th>Quote</th><th>Margin</th><th>Profit Guard</th><th>Updated</th></tr></thead><tbody>{estimates.map(e => <tr key={e.name} onClick={() => onEstimate(e)}><td><strong>{e.name}</strong><small>#MM-{e.name.length + 995}</small></td><td>{e.customer}</td><td>{formatMoney(e.cost)}</td><td>{formatMoney(e.quote)}</td><td>{e.margin.toFixed(1)}%</td><td><Status status={e.status}/></td><td>{e.updated}</td></tr>)}</tbody></table></div> }
function Status({ status }: { status: string }) { return <span className={`mm-status ${status === 'SAFE' || status === 'SAFE TO QUOTE' ? 'safe' : status === 'MARGIN RISK' ? 'risk' : 'danger'}`}><i/>{status}</span> }
function ProfitGuard() { return <><PageIntro eyebrow="PROFIT GUARD" title="Check a quote before it goes out." sub="Live pricing protection for the work you already know how to do."/><ProfitCalculator/></> }
function Estimates({ onScreen, onEstimate, saved, setSaved }: { onScreen:(s:Screen)=>void; onEstimate:(e:typeof estimates[number])=>void; saved:boolean;setSaved:(v:boolean)=>void }) { const [newEstimate, setNewEstimate] = useState(false); return <>{!newEstimate ? <><PageIntro eyebrow="ESTIMATES" title="Your quote workspace." sub="Review recent estimates or start a new one." action={<button className="mm-primary" onClick={() => setNewEstimate(true)}><Plus size={16}/> New Estimate</button>}/><section className="mm-panel"><div className="mm-panel-head"><div><span className="mm-eyebrow">ALL ESTIMATES</span><h3>{estimates.length + (saved ? 1 : 0)} estimates</h3></div><span className="mm-filter">Sample business data</span></div><EstimateTable onEstimate={onEstimate}/></section></> : <EstimateWorkspace onScreen={onScreen} saved={saved} setSaved={setSaved}/>}</> }
function EstimateWorkspace({ onScreen, saved, setSaved }: { onScreen:(s:Screen)=>void;saved:boolean;setSaved:(v:boolean)=>void }) { return <><PageIntro eyebrow="NEW ESTIMATE / MM-1005" title="Build the quote." sub="This estimate is temporary demo state — nothing is stored on a server." action={<button className="mm-secondary" onClick={() => onScreen('Proposals')}>Preview Proposal</button>}/><div className="mm-workspace-grid"><section className="mm-panel"><div className="mm-panel-head"><h3>Estimate details</h3><span className="mm-draft">{saved ? 'DRAFT SAVED' : 'UNSAVED DEMO'}</span></div><div className="mm-form-grid"><label>Customer<select><option>Sarah Chen</option><option>Tom Alvarez</option><option>Jordan Lee</option></select></label><label>Job name<input defaultValue="Bathroom Remodel"/></label><label className="full">Job description<textarea defaultValue="Primary bathroom renovation including tile, fixtures, and finish work."/></label></div><div className="mm-line-items"><h4>Line items</h4>{['General Labor · 24 hours','$2,640','Materials · Bathroom finish package','$1,900','Equipment / Subcontractors','$400'].map((x,i) => i%2===0 ? <div key={x}><span>{x}</span><strong>{['$2,640','$1,900','$400'][i/2]}</strong></div> : null)}</div><div className="mm-form-actions"><button className="mm-secondary" onClick={() => setSaved(true)}>Save Draft</button><button className="mm-primary" onClick={() => onScreen('Profit Guard')}><ShieldCheck size={15}/> Run Profit Guard</button></div></section><section className="mm-panel mm-mini-proposal"><span className="mm-eyebrow">CUSTOMER PREVIEW</span><h3>Miller Home Services</h3><p>Estimate #MM-1005 · Sarah Chen</p><hr/><strong>Bathroom Remodel</strong><p>Primary bathroom renovation including tile, fixtures, and finish work.</p><div><span>Estimated total</span><b>$6,500</b></div><small>Private costs and margin controls are hidden from the customer.</small></section></div></> }
function Customers({ selected, setSelected }: {selected:string|null;setSelected:(v:string|null)=>void}) { return <><PageIntro eyebrow="CUSTOMERS" title="Customer records." sub="A simple view of the people behind your work."/><section className="mm-panel"><div className="mm-panel-head"><h3>5 customers</h3><span className="mm-filter">Sample business data</span></div><div className="mm-table-wrap"><table className="mm-table"><thead><tr><th>Customer</th><th>Open Jobs</th><th>Estimates</th><th>Quoted Value</th><th>Last Activity</th></tr></thead><tbody>{customers.map(c => <tr key={c[0]} onClick={() => setSelected(c[0])}><td><strong>{c[0]}</strong><small>{c[0].toLowerCase().replace(' ','_')}@example.com</small></td><td>{c[1]}</td><td>{c[1]}</td><td>{c[2]}</td><td>{c[3]}</td></tr>)}</tbody></table></div></section>{selected && <div className="mm-detail"><button onClick={() => setSelected(null)}><X size={16}/></button><span className="mm-eyebrow">CUSTOMER DETAIL</span><h3>{selected}</h3><p>Sample customer record · 2 estimates · 1 open job</p><button className="mm-primary">New estimate</button></div>}</> }
function Jobs() { return <><PageIntro eyebrow="JOBS" title="Active work." sub="Keep an eye on the jobs connected to your estimates."/><section className="mm-panel"><div className="mm-panel-head"><h3>Active jobs</h3><span className="mm-filter">3 active</span></div><div className="mm-job-list">{[['Bathroom Remodel','Sarah Chen','In progress','$6,500','Mar 25'],['Kitchen Repair','Tom Alvarez','Scheduled','$2,100','Mar 29'],['HVAC Replacement','Priya Shah','Awaiting start','$8,300','Apr 02']].map(j => <div key={j[0]}><span><strong>{j[0]}</strong><small>{j[1]}</small></span><span>{j[2]}</span><b>{j[3]}</b><small>{j[4]}</small></div>)}</div></section></> }
function PriceBook({ search, setSearch, rows }: {search:string;setSearch:(v:string)=>void;rows:string[][]}) { return <><PageIntro eyebrow="PRICE BOOK" title="Reusable pricing items." sub="Standardize your costs and default selling prices."/><section className="mm-panel"><div className="mm-panel-head"><div><h3>8 demo items</h3></div><label className="mm-search"><Search size={15}/><input placeholder="Search price book" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="mm-table-wrap"><table className="mm-table"><thead><tr><th>Item</th><th>Category</th><th>Unit</th><th>Internal Cost</th><th>Default Selling Price</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td><strong>{r[0]}</strong></td><td>{r[1]}</td><td>{r[2]}</td><td>${Number(r[3]).toFixed(2)}</td><td>${Number(r[4]).toFixed(2)}</td></tr>)}</tbody></table></div></section></> }
function JobProfit() { return <><PageIntro eyebrow="JOB PROFIT" title="Estimated vs actual." sub="Understand where the job landed after the work is done."/><section className="mm-panel"><div className="mm-panel-head"><div><span className="mm-eyebrow">BATHROOM REMODEL</span><h3>Sarah Chen · #MM-1001</h3></div><span className="mm-status safe"><i/>PROFITABLE</span></div><div className="mm-profit-grid"><ProfitCompare label="Cost" estimated="$4,860" actual="$4,420" variance="−$440"/><ProfitCompare label="Profit" estimated="$1,640" actual="$2,080" variance="+$440" positive/><ProfitCompare label="Margin" estimated="25.2%" actual="32.0%" variance="+6.8 pts" positive/></div><div className="mm-bars"><div><span>Estimated cost</span><i style={{width:'78%'}}><b>$4,860</b></i></div><div><span>Actual cost</span><i className="actual" style={{width:'70%'}}><b>$4,420</b></i></div></div></section></> }
function ProfitCompare({label,estimated,actual,variance,positive=false}:{label:string;estimated:string;actual:string;variance:string;positive?:boolean}) { return <div className="mm-compare"><span>{label}</span><strong>{actual}</strong><small>Estimated {estimated}</small><b className={positive?'positive':''}>{variance}</b></div> }
function Proposal({ estimate }: {estimate:typeof estimates[number]}) { return <><PageIntro eyebrow="PROPOSALS" title="Customer-facing previews." sub="Keep internal profitability controls private while you present the work clearly."/><div className="mm-proposal"><div className="mm-proposal-head"><div><strong>Miller Home Services</strong><small>Professional home improvement</small></div><span>ESTIMATE #MM-1001</span></div><div className="mm-proposal-body"><span className="mm-eyebrow">PREPARED FOR</span><h3>{estimate.customer}</h3><h2>{estimate.name}</h2><p>Thank you for the opportunity to help with your project. Here is the scope and estimated investment for the work discussed.</p><div className="mm-proposal-lines"><div><span>Project services</span><b>{formatMoney(estimate.quote)}</b></div><div><span>Materials and finish work</span><b>Included</b></div><div className="total"><span>Total estimate</span><b>{formatMoney(estimate.quote)}</b></div></div><button className="mm-primary">Approve proposal <ArrowUpRight size={15}/></button></div></div></> }
function Upgrade() { return <><PageIntro eyebrow="FULL ACCESS" title="MarginMate, without the demo limits." sub="One-time founding access for contractors who want every quote to earn its keep."/><div className="mm-upgrade-card"><div><span className="mm-eyebrow">MARGINMATE FULL ACCESS</span><h3>$99</h3><p>One-time founding access</p></div><a className="mm-primary" href={MARGINMATE_CHECKOUT_URL} target="_blank" rel="noopener noreferrer">Get Full Access — $99 <ArrowUpRight size={15}/></a><div className="mm-includes">{['Profit Guard','True Cost Engine','Target Margin Engine','Saved Estimates','Customers & Jobs','Price Book','Proposal Preview','Expected vs Actual Job Profit','Core V1 improvements'].map(x=><span key={x}><ShieldCheck size={14}/>{x}</span>)}</div></div></> }
function About() { return <><PageIntro eyebrow="ABOUT MARGINMATE" title="Protect the work you already know how to do." sub="MarginMate is focused software for one expensive moment: deciding whether a quote is actually worth sending."/><div className="mm-about-grid"><div className="mm-panel"><span className="mm-eyebrow">WHY PROFIT GUARD?</span><h3>Revenue is not profit.</h3><p>Most estimating tools stop at the selling price. MarginMate starts with the costs that disappear into the job, then makes the pricing decision obvious.</p></div><div className="mm-panel"><span className="mm-eyebrow">DEMO STATE</span><h3>Explore without pretending.</h3><p>This public workspace uses sample business data. Drafts are temporary in this demo and no payment or account is created inside the preview.</p></div></div></> }

